language: rust
rust:
  - stable
sudo: false
env:
  global:
    - RUST_LOG=deribit=error
  matrix:
    - secure: aTVQ9EuS5tEbYjVK6a9MEewTixqRwBLJ3MW224lS0Fp1y6swge/c43+nyvNRwEAEFpBAaWysBFSYuRWOboTnfiBXVHdIAB6Tp39xnkew6rlYqdDxgavB58vcxj+WeSF/ujvgOjo5xneyvkJSad+M+M96BPKTE3AWl9cim8vcSNnbAwc6s2roKvXfeoCscOPjfQb7q33WojJlwXKOpmaaxUDnQu10lRKYgzzAeV5Hl+kONVk7zS4BAV684zWDagCBdrnzyDOXrxM368LeUa0p/PmRwZ/xBXm/1Yl8J547z6nGYit9E6TQrmMZ3URGKDSmzzror1tMIFmQVciaz1tG6S+knSosAFk34VePnwfz5Vl0abvDvbi931IrfzaymMRNhAoRd5N7a0GTnWzK3+5bdxXVExJ04kZ65zBqIa4Rn17zucM3+FbgSbWTXj5OTwRfqI4YPcZoZnaqQC8TXgSvj70CjqUG7Xu295vbQ1nRfVyPFxUyPD6Td5l4RbegvyRzCGZki8xQGXCB76yWAq/bjXZCL3tgJMUBYkqXJXtWaD80VLj33miSdonch+iGICQQjbQ4TcX7fIjmUsBPCSBvTmDYkYjofppKO0qdWRNq8o0jjz5lkirtuMsBx8kMUjvslQrPiaKc80SFnkJJ09VD3+v8yRe+17ctbYlJMrN2ir8=
