[package]
name = "deribit"
version = "0.1.10"
authors = ["Weiyüen Wu <doomsplayer@gmail.com>"]
edition = "2018"
description = "Rust client for deribit, nightly only. Please look at tests/examples for detail usage at current stage."
license = "MIT"
documentation = "https://docs.rs/deribit"
repository = "https://github.com/dovahcrow/deribit-rs"
readme = "README.md"

[dependencies]
futures = { version = "0.3", features = ["async-await"]}
tokio = "0.2.0-alpha.6"
tungstenite = { git = "https://github.com/snapview/tungstenite-rs.git" }
tokio-tungstenite = { git = "https://github.com/dovahcrow/tokio-tungstenite", version ="0.10.0-alpha.1", branch = "tokio2"}
url = "2"
serde = "1"
serde_json = "1"
serde_derive = "1"
failure = "0.1"
log = "0.4"
derive_builder = "0.8"
pin-project = "0.4"
shrinkwraprs = "0.2"
regex = "1"
lazy_static = "1"

[dev-dependencies]
env_logger = "0.7"
dotenv = "0.15"
fluid = "0.4"

